name: qwen_chat_openai
description: Chat FR ↔ ZH (zh-Hans) via OpenAI Chat Completions, UI type WhatsApp.
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.4.14
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  intl: ^0.20.2
  flutter_lints: ^6.0.0
  web_socket_channel: ^3.0.3
  flutter_local_notifications: ^19.5.0
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  http_parser: ^4.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.5.4
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/app_logo.svg
flutter_launcher_icons:
  android: true
  ios: false
  image_path_android: assets/icons/app_logo_1024.png
  adaptive_icon_background: "#0B2F28"
  adaptive_icon_foreground: assets/icons/app_logo_1024.png
  min_sdk_android: 21
