version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/qwen_chat_openai"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "github-actions"
    directory: "/qwen_chat_openai/.github/workflows"
    schedule:
      interval: "weekly"

