name: flutter-ci

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: qwen_chat_openai
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter Doctor
        run: flutter doctor -v

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Generate code (freezed/json)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test -r expanded -j 1

      # APK build requires full Android toolchain on CI; keep CI fast and stable
      # by limiting to analysis and tests. Release builds are produced locally.

