# Placeholder workflow to prevent GitHub Actions errors
# Previous workflows (analyze.yml, keepalive.yml) have been removed
# This file prevents "workflow not found" errors

name: Placeholder

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder step
        run: echo "No active workflows - project workflows have been removed"

